title = "Example"
description = "A complete example with input for EPT methods"

[mesh]
    size = [101,100,102,]
    step = [2e-3,2e-3,2e-3,]

[input]
    frequency = 297e6
    tx-channels = 1
    rx-channels = 1
    tx-sensitivity = 'tx_sens>.raw'
    trx-phase = 'trx_phase><.raw'
    reference-img = 'reference.raw'

    [input.wildcard]
        # the following are the default settings
        tx-character = '>'
        rx-character = '<'
        start-from = 0
        step = 1

[output]
    electric-conductivity = 'sigma.raw'
    relative-permittivity = 'epsr.raw'
