title = "Example"
description = "A complete example with input for EPT methods"

[mesh]
    size = [101,100,102,]
    step = [2e-3,2e-3,2e-3,]

[input]
    frequency = 297e6
    tx-channels = 1
    rx-channels = 1
    tx-sensitivity = 'example.h5:/input/tx_sens>'
    trx-phase = 'example.h5:/input/trx_phase><'
    reference-img = 'example.h5:/input/reference'

    [input.wildcard]
        # the following are the default settings
        tx-character = '>'
        rx-character = '<'
        start-from = 0
        step = 1

[output]
    electric-conductivity = 'example.h5:/output/sigma'
    relative-permittivity = 'example.h5:/output/epsr'
